
"use client";

import { useState, useEffect } from "react";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ReactMarkdown from 'react-markdown';

export default function MarketInsightsPage() {
  const [insight, setInsight] = useState<any>(null);
  const [language, setLanguage] = useState<'en' | 'ko'>('en');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchInsight();
  }, []);

  const fetchInsight = async () => {
    try {
      const res = await fetch('/api/market-insight/latest');
      if (res.ok) {
        const data = await res.json();
        setInsight(data);
      }
    } catch (error) {
      console.error("Failed to fetch insight", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="min-h-screen bg-white font-sans selection:bg-black selection:text-white">
      <Navbar theme="light" />

      <section className="pt-32 pb-12 px-6 bg-gray-50 border-b border-gray-200">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-4xl md:text-5xl font-serif text-black mb-6">
            Realtor&apos;s Investment Vision
          </h1>
          <p className="text-gray-600 text-lg font-light max-w-2xl mx-auto mb-8">
            Daily real estate trends, mortgage insights, and expert advice for the Bergen County luxury market.
          </p>

          {/* Language Toggle */}
          <div className="inline-flex rounded-full bg-white border border-gray-200 p-1 shadow-sm">
            <button
              onClick={() => setLanguage('en')}
              className={`px-6 py-2 rounded-full text-sm font-bold uppercase tracking-wider transition-all ${language === 'en'
                ? 'bg-black text-white shadow-md'
                : 'text-gray-400 hover:text-black'
                }`}
            >
              English
            </button>
            <button
              onClick={() => setLanguage('ko')}
              className={`px-6 py-2 rounded-full text-sm font-bold uppercase tracking-wider transition-all ${language === 'ko'
                ? 'bg-black text-white shadow-md'
                : 'text-gray-400 hover:text-black'
                }`}
            >
              한국어
            </button>
          </div>
        </div>
      </section>

      <section className="py-16 px-6 max-w-3xl mx-auto">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-12 space-y-4">
            <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-black"></div>
            <p className="text-sm text-gray-500 animate-pulse">Loading daily insights...</p>
          </div>
        ) : insight ? (
          <article className="prose prose-lg prose-gray mx-auto">
            <div className="text-sm text-gray-400 font-bold uppercase tracking-widest mb-8 border-b pb-4">
              Date: {new Date(insight.createdAt).toLocaleDateString()}
            </div>

            <div className="markdown-content">
              {/* Fallback to simple whitespace pre-wrap if react-markdown not installed, or check package.json */}
              {/* Since I am unsure if react-markdown is installed, I will use a simple whitespace div first to be safe,
                   or just simple rendering. Wait, I installed it? No, I haven't installed `react-markdown`.
                   I'll use whitespace-pre-line style for now to avoid dependency errors.
                */}
              <div className="whitespace-pre-wrap leading-relaxed font-light text-gray-800 text-lg">
                {language === 'en' ? insight.contentEn : insight.contentKo}
              </div>
            </div>

            <div className="mt-16 pt-8 border-t border-gray-100 flex flex-col md:flex-row justify-between text-xs text-gray-400 bg-gray-50 p-6 rounded-lg">
              <div className="mb-2 md:mb-0">
                <strong>AI Disclaimer:</strong> Content generated by Google Gemini Pro. Verify with professional advice.
              </div>
              <div>
                &copy; {new Date().getFullYear()} NJ Eunice Realty
              </div>
            </div>
          </article>
        ) : (
          <div className="text-center py-12 text-gray-500">
            <p>No insights available for today. Please check back later.</p>
          </div>
        )}
      </section>

      <Footer />
    </main>
  );
}
